### PR TITLE
Update rfc-publication-process.md

### PR DESCRIPTION
**Pull request by ajeanmahoney**
Clarified that technical edits are not expected once the document enters the queue. Fixed some typos.

### CODE REVIEW

**Comment by JayDaley** [comment]
Thanks for that.  There's only one thing I disagree with, which is removing any references to repositories.  I think we have lots of evidence that it's important for people to know that their repository is no longer authoritative once a doc enters AUTH48 and that would be best stated explicitly.  With the amended text it could be inferred that the authors repo remains authoritative but the RPC take over managing it.

**Comment by ajeanmahoney** [comment]
Not all authors use GitHub or GitLab repos, and I could see how someone could consider the datatracker to be the repo for the document, which why I wasn't comfortable with the statement "any repository the authors may have is no longer authoritative". The latest I-D in datatracker is the current version until the RFC is published. Sometimes there are technical changes that occur after the document is approved. We ask that the authors update the I-D in datatracker and then ask the stream manager to approve the new version.

**Comment by JayDaley** [comment]
This is the current sentence in your PR:
> This means that change control has passed to the RPC. If you have any nontechnical updates to make (for instance, you would like to update your contact information) you may reach the the RPC at rfc-editor@rfc-editor.org. Otherwise, once a document has entered the publication queue, technical updates are not expected and any such updates require stream approval.

And this is my proposed change:
> From this point on, the RPC has change control of the document.  This means that the RPC now manage the document in their own repository, and that all changes the authors wish to make must go through the RPC. Any non-technical changes, such as updating the contact information, will normally be accepted directly, but any technical updates will require stream approval.

My reasoning for the various changes are:
1. The rest of this page is not written as a set of instructions but as a description of a process and therefore the "you may reach ..." sticks out as inconsistent as it is an instruction.  Instructions, such as the specifics of how to contact the RPC are better left to the email that people receive when the enter AUTH48, not here, otherwise there are two sets of instructions that now need to be kept in sync.
2. It is now clear that RPC use their own repository.
3. The expectations around changes is still there, but in the descriptive style not instructional.

Does this work for you?

**Comment by ajeanmahoney** [comment]
I've updated the PR, thanks!

**Pull request merged**
